{% set name = "sasktran2" %}
{% set version = "2024.01.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usask-arg/sasktran2/archive/v{{ version }}.tar.gz
  sha256: a3167a2fa5ea830f207940d5196edbf449ad63833549ad1bca89ab2322592257

build:
  binary_relocation: true
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.5
    - make  # [not win]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not win]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - pip
    - eigen
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libtmglib
    - zlib
    - pybind11 >=2.10.2
    - spdlog
    - scikit-build-core
    - setuptools-scm
  run:
    - python
    - numpy
    - spdlog
    - fmt
    - appdirs
    - pyyaml
    - xarray
    - dask
    - netcdf4
    - scipy

test:
  imports:
    - sasktran2
  commands:
    - pip check
  requires:
    - pip

about:
  summary: The SASKTRAN radiative transfer model Version 2
  license: LicenseRef-SASKTRAN2
  license_file: license.md
  doc_url: https://sasktran2.readthedocs.io/
  home: https://github.com/usask-arg/sasktran2

extra:
  recipe-maintainers:
    - dannyzed
