context:
  version: "2025.8.0"
  python_min: '3.10'

# Note: This recipe is specifically designed to work well with the autotick bot.
# Also refer to https://github.com/conda-forge/rust-feedstock/blob/main/recipe/meta.yaml.
package:
  name: sasktran2
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sasktran2/sasktran2-${{ version }}.tar.gz
  sha256: 3833639239dfb146d967f20025fadeafb472e42b192d76cc7f462ad99e8f9b7a

build:
  number: 1
  skip:
    - not (match(python, python_min ~ ".*") and is_abi3)
  python:
    version_independent: true


requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.3.2,<2
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cmake
    - cargo-bundle-licenses
    - if: unix
      then:
        - make
    - if: build_platform == 'osx-64'
      then:
        - llvm-openmp
    - if: build_platform == 'linux-64'
      then:
        - libgomp
    - if: build_platform == 'win-64'
      then:
        - posix

  host:
    - python
    - python-abi3
    - pip
    - maturin >=1.3.2,<2
    - eigen
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libtmglib
    - zlib
    - spdlog
  run:
    - python
    - numpy
    - appdirs
    - pyyaml
    - xarray
    - netcdf4
    - scipy
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - python:
      pip_check: true
      imports:
        - sasktran2
      python_version: ${{ python_min }}.*
  - script:
      - python -c "from sasktran2 import *"

about:
  summary: The SASKTRAN radiative transfer model Version 2
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml
  documentation: https://sasktran2.readthedocs.io/
  homepage: https://github.com/usask-arg/sasktran2

extra:
  recipe-maintainers:
    - dannyzed
